"""Per-dataset data provenance.

Why this is not a boolean
-------------------------
A single ``is_synthetic`` flag cannot describe the normal state of this project. The
expected configuration is a *hybrid*: real Yahoo prices with no delivery%, no shares
outstanding and no sectors; real NSE participant flows denominated in *F&O
contracts* rather than cash rupees; and a cash FII/DII series that only spans
whatever has been accumulated since the API is current-day-only. A boolean forces a
lie in one direction or the other, and the direction that gets chosen by accident is
almost always "this is live data".

So provenance is recorded per dataset, with a status, a source string and a free
note, plus run-level caveats. Every script header and the HTML report read this
record. Nothing infers provenance from the mere existence of a parquet file: the
filesystem cannot tell you where bytes came from, and asserting otherwise is exactly
the failure mode this module exists to prevent.

ASCII discipline
----------------
Every string that can reach a console is normalised to ASCII. These banners print on
Windows terminals under cp1252, where a stray en-dash or rupee sign raises
``UnicodeEncodeError`` and takes down the whole run at the last line of output.
"""

from __future__ import annotations

import datetime as _dt
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Mapping

REAL = "real"
SYNTHETIC = "synthetic"
UNAVAILABLE = "unavailable"
STATUSES = (REAL, SYNTHETIC, UNAVAILABLE)

#: Filename of the machine-readable record, relative to the ``data`` directory.
PROVENANCE_FILENAME = "PROVENANCE.json"
#: Human-readable file GENERATED from the record. Never hand-edit it.
DATA_SOURCE_FILENAME = "DATA_SOURCE.md"
#: Legacy marker, written only when every recorded dataset is synthetic.
SYNTHETIC_MARKER = ".synthetic"

_ASCII_FOLD = {
    "₹": "Rs",   # rupee sign
    "–": "-",    # en dash
    "—": "--",   # em dash
    "‘": "'", "’": "'",
    "“": '"', "”": '"',
    "…": "...",
    " ": " ",
    "→": "->",
    "×": "x",
    "≥": ">=", "≤": "<=",
    "±": "+/-",
    "‑": "-",
}


def to_ascii(text: str) -> str:
    """Fold a string to pure ASCII, transliterating the characters we actually emit.

    Anything still non-ASCII becomes ``?`` rather than raising: a provenance banner
    must always print, because suppressing it is worse than printing it imperfectly.
    """
    for src, dst in _ASCII_FOLD.items():
        text = text.replace(src, dst)
    return text.encode("ascii", errors="replace").decode("ascii")


class ProvenanceError(Exception):
    """Raised on an invalid status or a malformed provenance record."""


@dataclass(frozen=True)
class DatasetOrigin:
    """Where one dataset came from.

    Attributes
    ----------
    status:
        ``real`` (fetched from the named source), ``synthetic`` (generated by
        :mod:`flowalpha.data.synthetic`), or ``unavailable`` (the field or series
        genuinely does not exist in the source we used -- e.g. delivery% from Yahoo).
    source:
        Free text, ideally a URL or API name. Shown verbatim in reports.
    note:
        Anything a reader needs in order not to misread the numbers -- above all,
        unit differences.
    """

    status: str
    source: str
    note: str = ""

    def __post_init__(self) -> None:
        if self.status not in STATUSES:
            raise ProvenanceError(f"invalid status {self.status!r}; expected one of {STATUSES}")

    def to_dict(self) -> dict[str, str]:
        return {"status": self.status, "source": self.source, "note": self.note}

    @classmethod
    def from_dict(cls, d: Mapping[str, str]) -> "DatasetOrigin":
        if "status" not in d:
            raise ProvenanceError(f"dataset record missing 'status': {dict(d)}")
        return cls(status=str(d["status"]), source=str(d.get("source", "")), note=str(d.get("note", "")))


@dataclass
class Provenance:
    """The run's data provenance record."""

    datasets: dict[str, DatasetOrigin] = field(default_factory=dict)
    caveats: list[str] = field(default_factory=list)
    updated_at: str | None = None
    #: True when no record was found on disk. Such a run must never claim live data.
    recorded: bool = True

    # -- mutation -----------------------------------------------------------
    def mark(self, dataset: str, status: str, source: str, note: str = "") -> "Provenance":
        """Record (or overwrite) one dataset's origin."""
        self.datasets[dataset] = DatasetOrigin(status=status, source=source, note=note)
        self.recorded = True
        return self

    def add_caveat(self, text: str) -> "Provenance":
        """Append a run-level caveat, de-duplicated."""
        text = text.strip()
        if text and text not in self.caveats:
            self.caveats.append(text)
        return self

    def drop(self, dataset: str) -> "Provenance":
        self.datasets.pop(dataset, None)
        return self

    # -- queries ------------------------------------------------------------
    def _names(self, status: str) -> list[str]:
        return sorted(n for n, o in self.datasets.items() if o.status == status)

    @property
    def real(self) -> list[str]:
        return self._names(REAL)

    @property
    def synthetic(self) -> list[str]:
        return self._names(SYNTHETIC)

    @property
    def unavailable(self) -> list[str]:
        return self._names(UNAVAILABLE)

    @property
    def any_synthetic(self) -> bool:
        return bool(self.synthetic)

    @property
    def all_synthetic(self) -> bool:
        """True only when there is at least one dataset and every one is synthetic.

        An empty record is not "all synthetic"; it is unrecorded.
        """
        return bool(self.datasets) and not (self.real or self.unavailable)

    @property
    def all_real(self) -> bool:
        return bool(self.datasets) and all(o.status == REAL for o in self.datasets.values())

    def status_of(self, dataset: str) -> str | None:
        origin = self.datasets.get(dataset)
        return origin.status if origin else None

    # -- presentation -------------------------------------------------------
    def label(self) -> str:
        """One-line ASCII description of what the run is actually built on."""
        if not self.recorded or not self.datasets:
            return "PROVENANCE UNRECORDED"
        if self.all_synthetic:
            return "SYNTHETIC DATA"
        if self.all_real:
            return "LIVE DATA"
        if self.synthetic:
            return "HYBRID: SYNTHETIC " + ", ".join(n.upper() for n in self.synthetic)
        # No synthetic datasets, but something is missing outright.
        return "LIVE DATA (PARTIAL: " + ", ".join(n.upper() for n in self.unavailable) + " UNAVAILABLE)"

    def tag(self) -> str:
        """Compact suffix for plot titles."""
        return to_ascii(f"[{self.label()}]")

    def banner(self) -> str:
        """One-line warning for console/report headers.

        Empty when every dataset is real and recorded -- there is nothing to warn
        about, and a banner that always fires stops being read.
        """
        if self.all_real:
            return ""
        if not self.recorded or not self.datasets:
            return to_ascii(
                "!! PROVENANCE UNRECORDED: data origin is unknown. Do not treat these "
                "numbers as live-market results until provenance is written."
            )
        if self.all_synthetic:
            return to_ascii(
                "!! SYNTHETIC DATA: all inputs are generated from a known DGP. "
                "Results validate the pipeline, not the market."
            )
        if self.synthetic:
            return to_ascii(
                "!! " + self.label() + ": some inputs are generated. Any result touching "
                "those datasets is not a live-market result."
            )
        return to_ascii(
            "!! " + self.label() + ": some inputs are missing, so the factors that "
            "depend on them are inert. See data/DATA_SOURCE.md."
        )

    def header(self, script_name: str) -> str:
        """Multi-line ASCII header for a CLI entry point."""
        lines = [
            "=" * 72,
            to_ascii(f"FlowAlpha :: {script_name}"),
            to_ascii(f"data provenance: {self.label()}"),
        ]
        banner = self.banner()
        if banner:
            lines.append(banner)
        lines.append("=" * 72)
        return "\n".join(lines)

    def describe(self) -> list[str]:
        """Per-dataset ASCII lines, for console dumps and report tables."""
        out = []
        for name in sorted(self.datasets):
            o = self.datasets[name]
            line = f"  {name:<20} {o.status:<12} {o.source}"
            if o.note:
                line += f"  ({o.note})"
            out.append(to_ascii(line))
        return out

    # -- persistence --------------------------------------------------------
    def to_dict(self) -> dict:
        return {
            "updated_at": self.updated_at,
            "label": self.label(),
            "datasets": {n: o.to_dict() for n, o in sorted(self.datasets.items())},
            "caveats": list(self.caveats),
        }

    @classmethod
    def from_dict(cls, d: Mapping) -> "Provenance":
        datasets = {
            str(n): DatasetOrigin.from_dict(v) for n, v in (d.get("datasets") or {}).items()
        }
        return cls(
            datasets=datasets,
            caveats=[str(c) for c in (d.get("caveats") or [])],
            updated_at=d.get("updated_at"),
            recorded=True,
        )

    @classmethod
    def unrecorded(cls) -> "Provenance":
        """The safe default when no record exists on disk."""
        return cls(datasets={}, caveats=[], updated_at=None, recorded=False)

    @classmethod
    def load(cls, data_dir: str | Path) -> "Provenance":
        """Read ``<data_dir>/PROVENANCE.json``, or return :meth:`unrecorded`.

        A missing or corrupt record yields ``PROVENANCE UNRECORDED``. It never
        yields ``LIVE DATA``.
        """
        path = Path(data_dir) / PROVENANCE_FILENAME
        if not path.exists():
            return cls.unrecorded()
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return cls.unrecorded()
        if not isinstance(raw, Mapping):
            return cls.unrecorded()
        try:
            return cls.from_dict(raw)
        except ProvenanceError:
            return cls.unrecorded()

    def save(
        self,
        data_dir: str | Path,
        *,
        timestamp: _dt.datetime | None = None,
        write_markdown: bool = True,
    ) -> Path:
        """Write the JSON record, regenerate ``DATA_SOURCE.md``, sync the legacy marker."""
        data_dir = Path(data_dir)
        data_dir.mkdir(parents=True, exist_ok=True)
        self.updated_at = (timestamp or _dt.datetime.now(_dt.timezone.utc)).isoformat()
        path = data_dir / PROVENANCE_FILENAME
        path.write_text(json.dumps(self.to_dict(), indent=2) + "\n", encoding="utf-8")
        if write_markdown:
            write_data_source_md(self, data_dir / DATA_SOURCE_FILENAME)
        sync_synthetic_marker(self, data_dir)
        return path


def sync_synthetic_marker(prov: Provenance, data_dir: str | Path) -> Path:
    """Create or remove the legacy ``.synthetic`` marker.

    The marker means "every dataset here is generated". It is written only when that
    is literally true and *removed* the moment any real dataset appears, because a
    stale marker on a hybrid tree is a provenance lie in the opposite direction.
    """
    marker = Path(data_dir) / SYNTHETIC_MARKER
    if prov.all_synthetic:
        marker.write_text(
            "All datasets in this tree are synthetic (see PROVENANCE.json).\n", encoding="utf-8"
        )
    elif marker.exists():
        marker.unlink()
    return marker


def write_data_source_md(prov: Provenance, path: str | Path) -> Path:
    """Generate the human-readable data-source document FROM the record.

    Generated, never hand-written, so the prose cannot drift away from the JSON. If
    you want to change what this says, change the record.
    """
    path = Path(path)
    lines: list[str] = [
        "# Data sources",
        "",
        "<!-- GENERATED FILE -- produced from data/PROVENANCE.json by",
        "     flowalpha.data.provenance.write_data_source_md. Do not hand-edit. -->",
        "",
        f"**Status: {prov.label()}**",
        "",
    ]
    banner = prov.banner()
    if banner:
        lines += [f"> {banner}", ""]
    lines += [f"_Record last updated: {prov.updated_at or 'never'}_", ""]

    if not prov.datasets:
        lines += [
            "No datasets are recorded. Until provenance is written, treat every number",
            "produced by this repository as being of unknown origin.",
            "",
        ]
    else:
        lines += ["| dataset | status | source | note |", "| --- | --- | --- | --- |"]
        for name in sorted(prov.datasets):
            o = prov.datasets[name]
            note = o.note.replace("|", "\\|") or "-"
            src = o.source.replace("|", "\\|") or "-"
            lines.append(f"| `{name}` | {o.status} | {src} | {note} |")
        lines.append("")

    counts = (
        f"{len(prov.real)} real, {len(prov.synthetic)} synthetic, "
        f"{len(prov.unavailable)} unavailable"
    )
    lines += [f"Dataset counts: {counts}.", ""]

    if prov.caveats:
        lines += ["## Caveats", ""]
        lines += [f"- {c}" for c in prov.caveats]
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(to_ascii("\n".join(lines)), encoding="utf-8")
    return path


def merge_caveats(prov: Provenance, caveats: Iterable[str]) -> Provenance:
    for c in caveats:
        prov.add_caveat(c)
    return prov


# ---------------------------------------------------------------------------
# Standing caveats. These are properties of the data sources this project uses,
# not of any particular run, so they live in code next to the record that carries
# them and get attached by whichever stage establishes the relevant fact.
# ---------------------------------------------------------------------------

CAVEAT_SURVIVORSHIP = (
    "Universe survivorship bias: NSE publishes only the CURRENT NIFTY 500 constituent "
    "list. Applied to a historical window this omits names that left the index and "
    "includes names that joined, for their whole history. Combined with post-2019 "
    "listings having no early history, per-rebalance cardinality GROWS over the sample. "
    "Returns are therefore biased upward by an unknown amount."
)

CAVEAT_FLOW_UNITS = (
    "Flow units: daily cash-market FII/DII history is not freely obtainable. The "
    "flows_daily and participant_flows series are built from NSE's participant-wise "
    "F&O file and are measured in NET FUTURES CONTRACTS (index + stock futures, long "
    "minus short; option legs excluded), not cash rupees. Regime features are "
    "quantile- and sign-based so bucketing is unaffected, but 'FII net' here means net "
    "futures positioning."
)

CAVEAT_DIVIDEND_ADJUSTMENT = (
    "Dividend adjustment is approximate: adj_factor = adj_close / close from Yahoo is "
    "applied to open/high/low. This is a proportional approximation, not a "
    "reconstruction of each corporate action."
)

CAVEAT_RETAIL_PROXY = (
    "Retail participation is proxied by the 'Client' participant category in NSE's F&O "
    "file. Client includes HNIs and proprietary-adjacent non-institutional accounts, so "
    "it is a proxy for retail, not a measurement of it."
)

CAVEAT_MULTIPLE_TESTING = (
    "Multiple testing: every factor and strategy evaluated is registered as a trial and "
    "Sharpe ratios are deflated against the cumulative trial count. IC t-statistics are "
    "reported RAW (Newey-West adjusted for autocorrelation only) and are NOT deflated."
)
